### PR TITLE
Fix Ably.purgeOldExpositions to clear tests even if none are running

### PR DESCRIPTION
**Pull request by aptomaKetil**
Previously, the loop on this.tests meant that purging wouldn't run if there were no active tests. Updated the method to ensure all scopes are always purged regardless of activity.

### CODE REVIEW

**Comment by aptomaKetil** [comment]
Ping @wadim

**Comment by wadim** [comment]
I cannot merge this.

This commit will make ably only purge elements of `this.scopes` and not scopes provided in configuration to each test. This is not a problem as long as tests only use the scopes from `this.scopes` but as soon as a test is added with a custom scope, the custom scope will not be managed.

A potential solution could be to add a `.registerScope()` with ably. This would add the scope to `.scopes` and make ably manage the scope. The existing scopes would be there by default but if you wanted to use a custom one, you would have the opportunity to put it under management.

What do you think, @aptomaKetil?

**Comment by aptomaKetil** [comment]
Right. I didn't realize you could specify custom scopes. I agree that this makes it trickier. I think having the option to let ably manage your custom scope is a good idea. Should I expand this PR, or add a separate one for `.registerScope()`.

**Comment by wadim** [comment]
Expand it.

**Comment by aptomaKetil** [comment]
Updated.

**Comment by aptomaKetil** [comment]
Ping.

**Pull request closed without merging**
